### PR TITLE
Replace Dashboard Icons with Custom Icons

### LINKED ISSUE #82: Replace Dashboard Icons with Custom Ones
We're currently using icons I picked up from Flaticon since the original design only had placeholders on it.

I believe @pat-riley suggested using the same ones we're using in the home page.

There's no legal issue with using these Flacicon icons since we're paying for a plan, but would like to check with @wdavidturner and @pat-riley

### PR DESCRIPTION
**Pull request by jwicks31**
Resolves #82

### CODE REVIEW

**Comment by wzalazar** [comment]
Can we check if the sizes are right?

screen shot 2018-05-24 at 13 53 40

**Comment by jwicks31** [comment]
There is more white-space surrounding the SVG images, so they are slightly smaller right now. Do we want to change that?

**Comment by wzalazar** [comment]
@lautarodragan can you check it with  @pat-riley?

**Comment by pat-riley** [comment]
Yea I think they could go a little bigger since these have more detail, I didn't use the exact illustrations in the attached image but it shows the relative sizing
screen shot 2018-05-24 at 2 10 05 pm

**Comment by wzalazar** [comment]
it's ok now @pat-riley ?

screen shot 2018-05-24 at 17 16 26

**Pull request merged**
