### PR TITLE
Toggle Mainnet/Testnet 

### PR DESCRIPTION
**Pull request by wzalazar**
[PR Process](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-process) - [PR Review Checklist](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-review-checklist)

## Description of Changes

Fix https://github.com/poetapp/frost-web/issues/156 https://github.com/poetapp/frost-web/issues/160 https://github.com/poetapp/frost-web/issues/248 https://github.com/poetapp/frost-web/issues/249 https://github.com/poetapp/frost-web/issues/254 https://github.com/poetapp/frost-web/issues/264

- updates the toggle Mainnet/Testnet
- Feature Toggle `?ft=toggle-network`

### Warning

Merging to `master` automatically triggers a deploy in production.

### CODE REVIEW

**Comment by jwicks31** [comment]
## PR Review Checklist


* [x] Tested changes manually
* [ ] Checked accidental architectural/style changes
* [x] Reviewed entire diff
* [x] Unit tests
* [ ] Documentation
* [x] Filenames and locations

### PR Reviewer Comments

**Comment by wzalazar** [comment]
@jwicks31 awesome!!! the manual test was successful

**Comment by lautarodragan** [comment]
Looking good, awesome work @jwicks31!

I tried this from the Netlify preview and it failed (which I understand is expected), but the error messages caught my eye:

image

No idea if this is being introduced in this branch or is already in master though.

**Comment by geoffturk** [comment]
@wzalazar ^^^^^^^^^^^^^^ Same issue we discussed yesterday.

**Comment by geoffturk** [comment]
@lautarodragan Merging #243 should resolve the issue above.

**Comment by wzalazar** [comment]
can you review again @lautarodragan?  any feedback?

**Comment by wzalazar** [comment]
@lautarodragan I will review if is necessary feature toggle here, in another hand if we want to keep the functionality with today, I will have to assume the api key doesn't have the `network` property is `mainnet`

**Comment by jwicks31** [comment]
@wzalazar I think once the feature toggles are all set we should be OK to merge to master because `network` is optional in `frost-client`.

**Comment by wzalazar** [comment]
@jwicks31 yes, with the FT, we can avoid sending the `network` and it will work

**Comment by wzalazar** [comment]
@warrenv can you help me with `Snyk`?

**Comment by wzalazar** [comment]
@lautarodragan @jwicks31 @warrenv is ready to review now

**Comment by warrenv** [comment]
Needs to have react-feature-toggles upgraded to 2.0 (not the beta as currently).
I believe @kennylavender told me a couple of weeks ago that this would involve some
work on frost-web due to the API changes in 2.0.

**Comment by kennylavender** [comment]
@warrenv, It looks like @wzalazar has already updated react-feature-toggles and feature-toggles to the latest versions. Maybe there is something else causing the vulnerabilites in snyk? or if its one of the feature-toggle packages I can run and update and publish a new version.

**Comment by kennylavender** [comment]
I just checked snyk for feature-toggles and react-feature-toggle current versions they don't have any vulnerabilities have been reported in the last 24 hours.

**Comment by warrenv** [comment]
The snyk vulnerability is for a dependency of react-feature-toggles.

**Comment by kennylavender** [comment]
@warrenv please provide more details on the vulnerabilities as I just re-ran the snyk checks on both feature-toggles and react-feature-toggles and its saying there is none.

**Comment by kennylavender** [comment]
Looks like snyk is thinks that the beta is still installed, maybe it needs to be retried or maybe an issue in the package-lock? not sure.

**Comment by wzalazar** [comment]
The problem is that we have `"webpack-dev-server": "1.16.5"`

screen shot 2018-09-11 at 12 46 53


but if we change the version to v3.1.8, we need to upgrade the version of `webpack` to v4 , there is this issue reported before https://github.com/poetapp/frost-web/issues/240

In this PR https://github.com/poetapp/frost-web/pull/263 passed the `snyk` task, but the development mode doesn't work

@geoffturk @warrenv 

What is the action we have to take now? I don't now exactly the effort to migrate the v3 to v4 of `Webpack`

**Comment by warrenv** [comment]
That's a really old version of webpack. We could get a lot performance improvements by upgrading to webpack 4. How hard do you think it would be @wzalazar?

**Comment by warrenv** [comment]
I'm ok with ignoring the snyk warning to get this merged in if everything else os looking ok. We can tackle snyk in another PR.

**Comment by wzalazar** [comment]
ready to review @lautarodragan @warrenv @jwicks31

**Pull request merged**
