### PR TITLE
adds testcafe and some e2e tests

### LINKED ISSUE #83: Add testcafe for e2e testing
- Install and configure Testcafe for end-to-end testing.
- Set the directory structure.
- Write one test that loads the home page and tests for an html attr unique to the page.

### PR DESCRIPTION
**Pull request by warrenv**
This commit:
  - Adds testcafe, an end-to-end testing tool.
  - Adds a 'test:e2e' script to `package.json`.
  - Sets the directory structure in `tests/functional`.
  - Demonstrates the use of [page objects](https://martinfowler.com/bliki/PageObject.html).
  - Adds some example tests:
      - Visit home page
      - Click on login/register button on home page.

Closes #83

### CODE REVIEW

**Comment by wzalazar** [comment]
@warrenv LGTM. We have an issue with lint in the test, no? Another observation is that we have to run this test in Travis. Do you want to do this tasks in other tickets?

**Comment by wzalazar** [comment]
Do we want to have javascript files instead of typescript in the tests?

**Comment by warrenv** [comment]
@wzalazar:
- I don't want to add these to Travis yet until we make sure they are going to be robust and not throw a bunch of non-deterministic errors.
- Yes, we want it to be javascript so we don't have to go thru the compile step. And we are interacting directly with the browser - what benefit would typescript bring in that situation?

**Comment by wzalazar** [comment]
@warrenv 

- ok, perfect with Travis.

- with regarding typescript in the test, we don't bring benefits. What do you think @lautarodragan?

**Pull request merged**
