### PR TITLE
bumps tslint-rules version

### PR DESCRIPTION
**Pull request by warrenv**

### CODE REVIEW

**Comment by wzalazar** [comment]
Can you add the immutable rules in this repository? All rules were fixed.

**Comment by warrenv** [comment]
I thought we agreed to address that at a future date?

**Comment by wzalazar** [comment]
Could you check if necessary this dependency now?

https://github.com/poetapp/frost-web/blob/32808383db3853e97fe66ce21701b3e3ed014ad4/package.json#L105

on the other hand, maybe we could deprecate this command

https://github.com/poetapp/frost-web/blob/32808383db3853e97fe66ce21701b3e3ed014ad4/package.json#L15

and move to the package.

if we decide this, we need to remove this dependencies,

https://github.com/poetapp/frost-web/blob/32808383db3853e97fe66ce21701b3e3ed014ad4/package.json#L93

https://github.com/poetapp/frost-web/blob/32808383db3853e97fe66ce21701b3e3ed014ad4/package.json#L103

**Comment by wzalazar** [comment]
with regarding the immutable rules we don't want to risk the code quality about this repository. We need to prevent insert new code than it does not comply the rules.

**Comment by warrenv** [comment]
Our top priority right now is to get a fully automated CI/CD pipeline
running. If we have to take step back on the linting rules, then that's
what we should do.

**Comment by wzalazar** [comment]
Excellent!!!

**Pull request merged**
