### PR TITLE
Update doc links

### PR DESCRIPTION
**Pull request by geoffturk**
[PR Process](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-process) - [PR Review Checklist](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-review-checklist)

## Description of Changes

Update links to docs & API.

### Warning

Merging to `master` automatically triggers a deploy in production.

### CODE REVIEW

**Comment by geoffturk** [comment]
@jwicks31 Any idea why this is failing?

**Comment by wzalazar** [comment]
@geoffturk you have this error `The command "npm run lint" exited with 2.`

you have to run `npm run lint:fix`

**Comment by geoffturk** [comment]
Thanks @wzalazar!

**Comment by geoffturk** [comment]
Still not working however. :-(

**Comment by wzalazar** [comment]
check out if you have the last dependencies in your local ;)

**Comment by geoffturk** [comment]
Doh! Classic PEBCAK. Thanks!

**Pull request merged**
